name: Compare functions
on: push
jobs:
    compare:
        runs-on: ubuntu-latest
        steps:
            - run: printenv | grep 'FUNC_' # 環境変数のリストを表示
              env:
                CONTAINS_FUNC: ${{ contains('Hello', 'ell') }} # 文字列に部分文字列が含まれるか
                STARTS_WITH_FUNC: ${{ startsWith('Hello', 'He') }} # 文字列が特定の接頭辞で始まるか
                ENDS_WITH_FUNC: ${{ endsWith('Hello', 'lo') }} # 文字列が特定の接尾辞で終わるか
                CONTAINS_FUNC2: ${{ contains(github.event.issue.labels.*.name, 'bug') }} # イシューのラベルに特定の文字列が含まれるか

            - run: printenv "${{ contains(github.event.issue.labels.*.name, 'bug') }}" # イシューのラベルに特定の文字列が含まれるかを表示
