name: Conditions
on: push
jobs:
    skip-or-run:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Hello6"
                echo ${{ github.run_id }} # ワークフロー実行IDの参照
              if: ${{ contains(github.run_id, '1') }} # ワークフロー実行IDで分岐
