name: Conditions workflow
on: push
jobs:
    skip-or-run:
        if: ${{ github.actor == 'octocat' }} # 実行ユーザーで分岐
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Hello"
